[package]
name = "nt3_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
native-windows-gui = { version = "1.0.12", features = ["raw-win-handle"] }
native-windows-derive = "1.0.3"
async-std = { version = "1.12.0", features = ["attributes"] }
zenoh = "1.0.0"
zenoh-ext = "1.0.0"